# fly.toml app configuration file generated for chat-app

app = "chat-app"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1